### ISSUE TITLE
Character Width not exported

### ISSUE THREAD

**Issue by naturally-intelligent** [burakyucel07/angelcode-fnt-generator#1]
On the character lines, I always get 0 for width:
char width=0
Should be default from the Character Dimensions X value?

**Comment by burakyucel07** [comment]
> On the character lines, I always get 0 for width: char width=0 Should be default from the Character Dimensions X value?

Hello. Sorry for the delay on answer. You should be able to get a non-zero width when you set the X Advance option from the tool. X Advance and the width will have the same value.

![xadvance](https://user-images.githubusercontent.com/31243110/211282028-1122e324-95a9-479a-8273-e32d94ed2ec7.jpg)

I tried with a basic bitmap font and I got this:

```
info face="a" size=9 bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth=0 aa=1 padding=0,0,0,0 spacing=0,0 outline=0
common lineHeight=9 base=0 scaleW=18 scaleH=9 pages=1 packed=0 alphaChnl=0 redChnl=0 greenChnl=0 blueChnl=0
page id=0 file="a.png"
chars count=3
char id=48 x=0 y=0 width=8 height=9 xoffset=0 yoffset=0 xadvance=8 page=0 chnl=15
char id=49 x=8 y=0 width=8 height=9 xoffset=0 yoffset=0 xadvance=8 page=0 chnl=15
char id=50 x=0 y=9 width=0 height=9 xoffset=0 yoffset=0 xadvance=0 page=0 chnl=15
kernings count=0

```

**Comment by JapanYoshi** [comment]
This implementation got me bugged behavior when exported. Please change the default behavior. https://github.com/godotengine/godot/issues/80815#issuecomment-1685788817

**Comment by burakyucel07** [comment]
@JapanYoshi Hello. I've tried exporting a .fnt file again and couldn't reproduce the problem even with the latest version. `xadvance` and `width` values are correct. Can you please try the version 0.0.2 that I recently added?

If the problem persists for you, can you please add your reproduction steps? This project was a simple project that I use on my Godot Engine games, so I am aware that it needs some user experience improvements.
